language: ruby
services:
  - postgresql
before_install:
  - gem update bundler
install: bundle install
before_script:
  - psql -c 'create database queue_classic_plus_test;' -U postgres

rvm:
  - 2.7.1
  - 2.6.5
  - 2.5.7
