language: ruby
services:
  - postgresql
before_install:
  - gem update bundler
install: bundle install --without development
before_script:
  - psql -c 'create database queue_classic_plus_test;' -U postgres

rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9
